spring.application.name=proyecto1_archivos_ss26
spring.datasource.url=jdbc:postgresql://localhost:5432/db_empresa_muebles
spring.datasource.username=postgres
spring.datasource.password=1postgre-sql-18
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
